### ISSUE TITLE
Copying .htaccess to public directory

### ISSUE THREAD

**Issue by dailysleaze** [themsaid/katana-core#5]
Currently dot files (specifically .htaccess) aren't copied from /content to /public as Laravel is set to ignore them in the filesystem class. It would need `->ignoreDotFiles(false)` adding in here: https://github.com/laravel/framework/blob/5.2/src/Illuminate/Filesystem/Filesystem.php#L352. There is also no exposure to this Symfony method via the Laravel class.

So there currently isn't any way to get the .htaccess file into the public directory as every build it is deleted and not re-copied.

I'm not sure if you would want to copy all dot files by extending `Illuminate\Filesystem` or to hard code copying .htaccess if it exists?

**Comment by themsaid** [comment]
Here's a patch to fix that: https://github.com/themsaid/katana-core/releases/tag/v1.2.4

**Comment by dailysleaze** [comment]
That's brilliant. Thanks!
